name: tl_ntlm_dio
description: Dio Interceptor to NTLM-auth
version: 1.0.0
homepage:

environment:
  sdk: '>=2.2.0 <4.0.0'

dependencies:
  dio: any
  dio_cookie_manager: ^1.0.0
  logging: ">=0.11.3+2 <1.0.0"
  ntlm: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.6.2
  system_info: ^0.1.0

flutter:
