name: tl_ntlm_dio
description: Dio Interceptor to NTLM-auth
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: any
  dio_cookie_manager: any
  logging: any
  ntlm:
    git:
      url: https://github.com/Neikan/ntlm.git
      ref: master
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.6.2


flutter:
